
const quotes = [
  { id: 1, quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
  { id: 2, quote: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
  { id: 3, quote: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
  { id: 4, quote: "Get busy living or get busy dying.", author: "Stephen King" },
  { id: 5, quote: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
  { id: 6, quote: "Many of life's failures are people who did not realize how close they were to success when they gave up.", author: "Thomas A. Edison" },
  { id: 7, quote: "If you want to live a happy life, tie it to a goal, not to people or things.", author: "Albert Einstein" },
  { id: 8, quote: "Never let the fear of striking out keep you from playing the game.", author: "Babe Ruth" },
  { id: 9, quote: "Money and success don't change people; they merely amplify what is already there.", author: "Will Smith" },
  { id: 10, quote: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
  { id: 11, quote: "Not how long, but how well you have lived is the main thing.", author: "Seneca" },
  { id: 12, quote: "If life were predictable it would cease to be life, and be without flavor.", author: "Eleanor Roosevelt" },
  { id: 13, quote: "The whole secret of a successful life is to find out what is one's destiny to do, and then do it.", author: "Henry Ford" },
  { id: 14, quote: "In order to write about life first you must live it.", author: "Ernest Hemingway" },
  { id: 15, quote: "The big lesson in life, baby, is never be scared of anyone or anything.", author: "Frank Sinatra" },
  { id: 16, quote: "Sing like no one's listening, love like you've never been hurt, dance like nobody's watching, and live like it's heaven on earth.", author: "Mark Twain" },
  { id: 17, quote: "Curiosity about life in all of its aspects, I think, is still the secret of great creative people.", author: "Leo Burnett" },
  { id: 18, quote: "Life is not a problem to be solved, but a reality to be experienced.", author: "Søren Kierkegaard" },
  { id: 19, quote: "The unexamined life is not worth living.", author: "Socrates" },
  { id: 20, quote: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
  { id: 21, quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { id: 22, quote: "Don't cry because it's over, smile because it happened.", author: "Dr. Seuss" },
  { id: 23, quote: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
  { id: 24, quote: "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.", author: "Albert Einstein" },
  { id: 25, quote: "Be who you are and say what you feel, because those who mind don't matter, and those who matter don't mind.", author: "Bernard M. Baruch" },
  { id: 26, quote: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { id: 27, quote: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
  { id: 28, quote: "If you tell the truth, you don't have to remember anything.", author: "Mark Twain" },
  { id: 29, quote: "Friendship is born at that moment when one person says to another, 'What! You too? I thought I was the only one.'", author: "C.S. Lewis" },
  { id: 30, quote: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", author: "Eleanor Roosevelt" },
  { id: 31, quote: "A successful man is one who can lay a firm foundation with the bricks others have thrown at him.", author: "David Brinkley" },
  { id: 32, quote: "Those who dare to fail miserably can achieve greatly.", author: "John F. Kennedy" },
  { id: 33, quote: "I can't give you a sure-fire formula for success, but I can give you a formula for failure: try to please everybody all the time.", author: "Herbert Bayard Swope" },
  { id: 34, quote: "It is hard to fail, but it is worse never to have tried to succeed.", author: "Theodore Roosevelt" },
  { id: 35, quote: "Love the life you live. Live the life you love.", author: "Bob Marley" },
  { id: 36, quote: "The most difficult thing is the decision to act, the rest is merely tenacity.", author: "Amelia Earhart" },
  { id: 37, quote: "Every strike brings me closer to the next home run.", author: "Babe Ruth" },
  { id: 38, quote: "Definiteness of purpose is the starting point of all achievement.", author: "W. Clement Stone" },
  { id: 39, quote: "We must balance conspicuous consumption with conscious capitalism.", author: "Kevin Kruse" },
  { id: 40, quote: "Life is what we make it, always has been, always will be.", author: "Grandma Moses" },
  { id: 41, quote: "The question isn't who is going to let me; it's who is going to stop me.", author: "Ayn Rand" },
  { id: 42, quote: "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.", author: "Henry Ford" },
  { id: 43, quote: "Too many of us are not living our dreams because we are living our fears.", author: "Les Brown" },
  { id: 44, quote: "I have learned over the years that when one's mind is made up, this diminishes fear.", author: "Rosa Parks" },
  { id: 45, quote: "I didn't fail the test. I just found 100 ways to do it wrong.", author: "Benjamin Franklin" },
  { id: 46, quote: "If you're offered a seat on a rocket ship, don't ask what seat! Just get on.", author: "Sheryl Sandberg" },
  { id: 47, quote: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
  { id: 48, quote: "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.", author: "Plato" },
  { id: 49, quote: "Nothing is impossible, the word itself says 'I'm possible!'", author: "Audrey Hepburn" },
  { id: 50, quote: "I think, therefore I am.", author: "René Descartes" }
];
export function generateComments(){
    return quotes[Math.floor(Math.random() * quotes.length)]
}
